# To setup the database, execute the following instead
# docker exec -i myblog-db sh -c 'mysql -uroot -p$MYSQL_ROOT_PASSWORD' < setup.sql
#
# To test setup, execute
# docker exec -i myblog-db sh -c 'mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "SHOW TABLES;" $MYSQL_DATABASE'
# 
# To connect to mysql database execute the following
# docker exec -it myblog-db sh -c 'mysql -uroot -p$MYSQL_ROOT_PASSWORD'
#
# mysql> show databases;
# mysql> use myblog;
# mysql> show tables;
# mysql> select * from users;

name: "myblog"
services:
  db:
    image: mysql:latest
    container_name: myblog-db
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - "3306:3306"